def cceROQuery(yyyyMMIn, additionalParams=0):
	additionalParamsQry='''
		, roEntry.RHCLBA as LABORPAY
		, roEntry.RHCPTA as PARTPAY 
		, roEntry.RHCSBA as MISCPAY
		, case when roEntry.RHTIM1 ='0001-01-01 00:00:00' then NULL else roEntry.RHTIM1 end as ROOPENTIME
		, case when roEntry.RHTIM2 ='0001-01-01 00:00:00' then NULL else roEntry.RHTIM2 end as ROCLOSETIME
	'''
	additionalParamsQry_1='''
		, roEntry.RHCLBA
		, roEntry.RHCPTA 
		, roEntry.RHCSBA
		, roEntry.RHTIM1
		, roEntry.RHTIM2
	'''

	if additionalParams==0:
		additionalParamsQry=''
		additionalParamsQry_1=''

	queryTemp='''
		SELECT A.RORDLRO as DEALER_CD
			, TRIM(A.ROSEQNO) as REPAIR_ORDER_NUM
			, A.ROFVINO as VIN
			, SUBSTRING(A.ROWODTO, 5, 2) || '/' || SUBSTRING(A.ROWODTO, 7, 2) || '/' || SUBSTRING(A.ROWODTO, 1, 4) as RO_OPEN_DATE
			, SUBSTRING(roEntry.RHWCDT, 5, 2) || '/' || SUBSTRING(roEntry.RHWCDT, 7, 2) || '/' || SUBSTRING(roEntry.RHWCDT, 1, 4) as RO_CLOSE_DATE
			, A.CCEROFLAG as CCERO_FLAG
			{1}
		FROM CAPDAT.CAROHP roEntry 
		JOIN
		(
			Select CAPDAT.CAROOP.RORDLR RORDLRO
				, CAPDAT.CAROOP.ROSEQN ROSEQNO
				, CAPDAT.CAROOP.ROWODT ROWODTO
				, CAPDAT.CAROOP.ROFVIN ROFVINO
				, 'Y' As CCEROFLAG 
			From CAPDAT.CAROOP 
			Where 
					(CAPDAT.CAROOP.RODOPC Like '%HE400%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE402%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE304%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE100%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE301%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE200%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE99P%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE600%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE500%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE700%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE800%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE603%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE401%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE303%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE1000%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HQ902%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE602%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HQ900%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HQ901%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE601%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE302%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE501%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE201%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE204%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE203%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE202%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE205%' 
					Or CAPDAT.CAROOP.RODOPC Like '%HE206%'
			) 
			UNION 
			SELECT CAPDAT.CAROOP.RORDLR RORDLRO
				, CAPDAT.CAROOP.ROSEQN ROSEQNO
				, CAPDAT.CAROOP.ROWODT ROWODTO
				, CAPDAT.CAROOP.ROFVIN ROFVINO
				, 'Y' As CCEROFLAG 
			FROM CAPDAT.CAROOP 
			WHERE 
				CAPDAT.CAROOP.RORDLR In ('AZ046', 'GA065', 'TX181', 'GA075') 
				And (CAPDAT.CAROOP.RODOPC Like '%11HYZ%' 
					Or CAPDAT.CAROOP.RODOPC Like '%MA83%' 
					Or CAPDAT.CAROOP.RODOPC Like '%09HYZ%' 
					Or CAPDAT.CAROOP.RODOPC Like '%01HYZ005%' 
					Or CAPDAT.CAROOP.RODOPC Like '%MA40%' 
					Or CAPDAT.CAROOP.RODOPC Like '%MULTI-A%' 
					Or CAPDAT.CAROOP.RODOPC Like '%00HYZ10%') 
			UNION 
			SELECT CAPDAT.CAROOP.RORDLR RORDLRO
				, CAPDAT.CAROOP.ROSEQN ROSEQNO
				, CAPDAT.CAROOP.ROWODT ROWODTO
				, CAPDAT.CAROOP.ROFVIN ROFVINO
				, 'Y' As CCEROFLAG 
			FROM CAPDAT.CAROOP 
			WHERE 
				CAPDAT.CAROOP.RORDLR In ('NM011', 'NM012', 'AZ019') 
				And CAPDAT.CAROOP.ROOPGP Like 'CCE%'
		) A on A.ROSEQNO=roEntry.RHSEQN 
			and roEntry.RHRDLR = A.RORDLRO
			and roEntry.RHFVIN = A.ROFVINO
			and roEntry.RHWODT = A.ROWODTO
			and INT(roEntry.RHWCDT/100)={0}
		Group By A.RORDLRO
		, A.ROSEQNO
		, A.ROFVINO
		, A.ROWODTO
		, A.CCEROFLAG
		, roEntry.RHWCDT
		{2}
	'''.format(yyyyMMIn, additionalParamsQry, additionalParamsQry_1)
	return queryTemp